### ISSUE TITLE
Unable to Load Module on M1 Mac

### ISSUE THREAD

**Issue by irv075** [curityio/nginx_oauth_proxy_module#15]
Using a docker image of nginx 1.21.3 on a Mac with an M1 chip we are unable to load the module. Error message:

`nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_curity_http_oauth_proxy_module.so" failed (/etc/nginx/modules/ngx_curity_http_oauth_proxy_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:7`

The module itself is mounted to the correct location, so I assume it is a dependency that cannot be found.

Tried with amzn, amzn2 and Ubuntu modules. We've also previously tried an Alpine image with the Alpine module, but we've had issues with other Alpine images on M1 before so kind of expected that to fail.

Does the module need to be compiled specifically for machines with the M1 chip?

**Comment by gary-archer** [comment]
I suspect this is not specific to an M1 chip but instead related to the path you are copying the module to, which is different depending on the Linux distro. Hopefully the deployment resources will help you to structure your Docker deployment and resolve your issue:

- [Deployment Wiki](https://github.com/curityio/nginx_oauth_proxy_module/wiki/4.-Docker-Deployment) - with notes on how to test deployment for each distro
- [Deployment Script](https://github.com/curityio/nginx_oauth_proxy_module/blob/main/resources/deployment/deploy.sh) - which shows the expected module folders

According to this deployment testing we did at Curity, these are the locations for each of the distros:

- amzn: /usr/local/nginx/modules
- amzn2: /etc/nginx/modules
- ubuntu: /usr/lib/nginx/modules

Try downloading the file at this URL and then saving it to the `./build` folder:

https://github.com/curityio/nginx_oauth_proxy_module/releases/download/1.0.0/amzn2.ngx_curity_http_oauth_proxy_module_1.21.3.so

Then run this command to test the deployment:

```bash
./resources/deployment/deploy.sh amazon2
./resources/deployment/test.sh
```

Then run this command to test the deployment:

**Comment by irv075** [comment]
Thanks Gary, I'll get one of the team with a Mac to give this a go 👍🏻
