### ISSUE TITLE
Simple Same-Origin Requests Fail Due to Origin Check

### ISSUE THREAD

**Issue by irv075** [curityio/nginx_oauth_proxy_module#23]
When making a same origin GET request, the `Origin` header will not be sent by the client. However, because the module checks for the existence of that header, a 401 response is generated.

e.g. a GET request from a SPA at `demo1.example.com/orders` to an api endpoint at `demo1.example.com/api/v1/orders` will fail because the `Origin` header is not set.

Should the origin check be disabled for non-cors requests?

**Comment by gsahbi** [comment]
Had the same #24 
I ended up tweaking the code to ignore origin checks if header does not exist.

after all, cors is a ua security enforcement so we have to trust the browser logic.

**Comment by gary-archer** [comment]
Thanks for pointing this out. We will be providing a new release with a fix in the coming days, once we've done some testing.
