### ISSUE TITLE
Browser does not send Origin header for fetch GET

### ISSUE THREAD

**Issue by gsahbi** [curityio/nginx_oauth_proxy_module#24]
This assumption that all modern browsers send Origin by default is not true.

https://github.com/curityio/nginx_oauth_proxy_module/blob/42c60b8f97490bf8b00f88661d3ba1fd4a4856e8/src/oauth_proxy_handler.c#L74

As per MDN documentation of fetch API https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

Quote:

Broadly speaking, user agents add the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) request header to:

- [cross origin](https://developer.mozilla.org/en-US/docs/Glossary/CORS) requests.
- [same-origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) requests except for [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) or [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests (i.e. they are added to same-origin [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST), [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS), [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT), [PATCH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH), and [DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) requests).

End Quote

**Comment by gary-archer** [comment]
Thanks for pointing this out. We will be providing a fix in the coming days.
